# Book settings
title: Python Basics
author: AI-generated
logo: ../icon.png
copyright: "2024"
only_build_toc_files: true

# Execution settings
execute:
  execute_notebooks: force

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true

# Launch button settings
repository:
  url: https://github.com/generated-books/python-basics
  branch: main

# Advanced and power-user settings
sphinx:
  config:
    html_last_updated_fmt: "%B %d, %Y"

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist