# Book settings
title: Python Basics and Data Science Fundamentals
author: AI-Generated
logo: ../icon.png
copyright: "2024"
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/generated-books/python-basics
  path_to_book: docs

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""

# Date of last update
last_updated: "June 23, 2024"